2022-09-14T10:55:24.115829+0300 | ERROR | An error has been caught in function 'main', process 'MainProcess' (1824), thread 'MainThread' (3128):
Traceback (most recent call last):

  File "c:\python\DominosPars\googlesheetspars\main.py", line 67, in <module>
    main()
    └ <function main at 0x000000DE56034820>

> File "c:\python\DominosPars\googlesheetspars\main.py", line 62, in main
    delenie(1, 0)
    └ <function delenie at 0x000000DE56034550>

  File "c:\python\DominosPars\googlesheetspars\main.py", line 58, in delenie
    return a/b
           │ └ 0
           └ 1

ZeroDivisionError: division by zero
